config/routes.rb
Rails.application.routes.draw do
  resources :jokes
  resources :likes
  resources :dislikes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "jokes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dis_like.rb
class DisLike < ApplicationRecord
  belongs_to :joke
end

app/models/joke.rb
class Joke < ApplicationRecord
    has_many :likes
    has_many :dis_likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :joke
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
    def create
        @dislike = DisLike.new(dislike_params)

        if !@dislike.save
            flash[:notice] = @dislike.errors.full_messages.to_sentence
        end 
        
        redirect_to Joke
    end  
    
    private
        def dislike_params
            params.require(:dis_like).permit(:joke_id)
        end    
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: %i[ show edit update destroy ]

  # GET /jokes or /jokes.json
  def index
    @random_joke = Joke.order("RANDOM()").first
    @jokes = Joke.all
  end

  # GET /jokes/1 or /jokes/1.json
  def show
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit
  end

  # POST /jokes or /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, notice: "Joke was successfully created." }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1 or /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to @joke, notice: "Joke was successfully updated." }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1 or /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_url, notice: "Joke was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_joke
      @joke = Joke.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def joke_params
      params.require(:joke).permit(:joke_content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = Like.new(like_params)

        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end   
        
        redirect_to Joke
    end 
    
    private

        def like_params
            params.require(:like).permit(:joke_id)
        end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/jokes/_form.html.erb
<%= form_with(model: joke) do |form| %>
  <% if joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
        <% joke.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :joke_content %>
    <%= form.text_area :joke_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

app/views/jokes/index.html.erb
<div class="card border-0 main-joke">
  <div class="card-body">
    <div class="joke-content">
        <p><%= @random_joke.joke_content %></p>
    </div>

    <div class="buttons-container border-top p-4">
      <div class="buttons">
        <div class="btnLike">
              <%= button_to "This is Funny!", likes_path, params: { like: { joke_id: @random_joke.id}}, method: :post, class:"btn btn-primary" %>
       </div>   

       <div class="btnDislike">    
              <%= button_to "This is not funny.", dislikes_path, params: { dis_like: { joke_id: @random_joke.id}}, method: :post, class:"btn btn-notfun" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Joke content:</strong>
  <%= @joke.joke_content %>
</p>

<%= link_to 'Edit', edit_joke_path(@joke) %> |
<%= link_to 'Back', jokes_path %>

app/views/layouts/_footer.html.erb
<footer class="d-flex justify-content-center border-top border-bottom border-1 mb-3">
    <div class="text-center footer-content text-secondary">
        <p>
            This website is created as part of HLSolutions program. The materials contained on this website
            are provided for general information only and do not constitute any form of advice. HLS assumes no
            responsibility for the accuracy of any particular statement and accepts no liability for any loss or
             damage which may arise from reliance on the information contained on this site.
        </p>
        <p class="mb-0"><b>Copyright 2021 HLS</b></p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
        <div class="images-container d-flex justify-content-between">
            <div class= "imgs">
                 <%= image_tag("logo.png") %>
            </div>
           <div class= "imgs">
                 <%= image_tag("leaf.jpg", class: "userImg") %>
            </div>
            
        </div>
        <div class="header-content text-white text-center">
            <h2>A joke a day keeps the doctor away</h2>
            <p>If you joke wrong way, your teeth have to pay. (Serious)</p>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomJoke</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid p-0">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>